name: CI - Testes de UI (Selenium)

on:
  push:
    branches: [ "main" ]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código deste repositório (Projeto 3)
      - name: 1. Checkout UI Test Project (Projeto 3)
        uses: actions/checkout@v4

      # 2. Configura o Java 17
      - name: 2. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Roda os Testes de UI (Selenium)
      - name: 3. Run E2E UI Tests (Selenium)
        run: |
          # Dá permissão de execução (A CORREÇÃO)
          chmod +x mvnw
          # Roda o teste (o BrowserHooks "inteligente" vai usar o headless)
          ./mvnw test