# 1. Nome do Workflow
name: Selenium UI Test CI

# 2. Gatilho (Trigger)
#    Roda a cada 'push' na branch 'main' DESTE projeto
on:
  push:
    branches: [ "main" ]

# 3. Tarefas (Jobs)
jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    # 4. Passos (Steps)
    steps:
      # Passo 1: Baixar o código de teste (Projeto 3)
      - name: Checkout Test Repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # ---- INÍCIO DAS ETAPAS DE UI ----

      # Passo 3: Instalar o Google Chrome
      # (O WebDriverManager precisa que o Chrome esteja instalado)
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          # Instala a versão 'stable' mais recente
          chrome-version: stable

      # Passo 4: Rodar os Testes de UI (Selenium + Cucumber)
      - name: Run UI Tests with Maven
        # Adicionamos 'options: -D"chromeoptions.args=--headless"'
        # para forçar o Selenium a rodar sem abrir uma janela gráfica
        run: ./mvnw test -D"chromeoptions.args=--headless"